spring:
  profiles:
    active:
    - prod
  flyway:
    enabled: true
    url: jdbc:mysql://hk-mysql:3306/place?useSSL=false
    user: root
    password: root
    locations:
      - classpath:db/migration/mysql
    schemas:
      - place
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://hk-mysql:3306/place?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
foursquare:
  id: N5RKMW0SND4TG0ROIGBEQK5OZGZB2EPWQLTX05YWY0ZJ4YTX
  secret: TIXAYKTY4NILY0W5TAY2IU4PK4XHG4Q2J5ZGSPLLCPQL0D4Y
  version: 20180323
  
---
spring:
  profiles:
    active:
    - test
  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3306/place?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    user: root
    password: 12345678
    locations:
      - classpath:db/migration/mysql
    schemas:
      - place
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    
foursquare:
  id: N5RKMW0SND4TG0ROIGBEQK5OZGZB2EPWQLTX05YWY0ZJ4YTX
  secret: TIXAYKTY4NILY0W5TAY2IU4PK4XHG4Q2J5ZGSPLLCPQL0D4Y
  version: 20180323
